EOSIO/eosio.cdt

- libraries/eosiolib/types.hpp
`"foo"_n` is a shortcut for `name{eosio::string_to_name("foo")}`
The `N` macro has the following issues:
* `N(foo)` confuses new users; they wonder where the identifier `foo` is defined. They're shocked when they learn `foo` isn't an identifier.
* `N` returns a `uint64_t` instead of a `name`. This hurts type safety.
> _n literal operator

- libraries/eosiolib/asset.hpp
- libraries/eosiolib/currency.hpp
- libraries/eosiolib/symbol.hpp
`extended_symbol` and `extended_asset` used to inherit from `symbol` and `asset`. The implicit conversions led to bugs, e.g. in comparison operators. They now use containment instead.
They also used to use `account_name` (`uint64_t`), which isn't type safe. They now use the `name` struct instead.
Partially fixes https://github.com/EOSIO/eos/issues/4525; other types aren't yet audited for problems.
> extended_symbol and extended_asset no longer inherit

- build.sh
FREE_MEM gets wrong value if LOCALE is distinct of English.
In spanish I get this error:
```bash
./build.sh: línea 70: /4000000 : error sintáctico: se esperaba un operando (el elemento de error es "/4000000 ")
./build.sh: línea 71: 4 <  ? 4 :  : error sintáctico: se esperaba un operando (el elemento de error es "? 4 :  ")
```
> fix: FREE_MEM

- libraries/libc++/CMakeLists.txt
added minimal printf/sprintf/snprintf. This will allow users to use these in their contracts without the stack overflow problem.  Removed sstream to keep users from trying to use this until it can be fixed properly.  Added __cxa_pure_virtual to libcxx to allow for pure virtual methods.
> minimal s*printf/printf also remove sstream from libcxx for now

- examples/abigen_test/abitest.cpp
- libraries/eosiolib/symbol.hpp
- libraries/libc++/CMakeLists.txt
- Fixes for abigen #149 
- Added stub for __cxa_pure_virtual, currently asserts with the message "called pure virtual".
- Added warnings to sstream, regex, strstream for code size increase if used.
- Added error to iostream to that it will clash with eosio::datastream.
- Patched locale to allow compilation and linking with stringstreams, regex, etc.
- Added symbol constructor to use std::string_view.
> quick fixes

- libraries/eosiolib/action.hpp
If no operator <, `std::set<eosio::permission_level>` can't compile. It's used in `<eosiolib/permission.hpp>`.
> support std::set<eosio::permission_level>

- docker/Dockerfile
- docker/install_deb.sh
This Dockerfile create an image based on the latest release by default. The release can be overridden by specifying ```--build-arg release=<tag>``` when building the image.
> Add Dockerfile for generating docker image.

- libraries/eosiolib/crypto.h
- libraries/eosiolib/crypto.hpp
- libraries/eosiolib/datastream.hpp
- libraries/eosiolib/fixed_bytes.hpp
- libraries/eosiolib/fixed_key.hpp
- libraries/eosiolib/multi_index.hpp
- libraries/eosiolib/print.hpp
- tools/include/eosio/gen.hpp
The (de)serialization of `eosio::key256` was implemented in a way which was not intended. The raw bytes of the inner `uint128_t` array were copied without modification. Because WASM is little endian, this means that the byte sequence of the serialized data was not MSB to LSB but rather mixed up. 
The MSB to LSB order is expected for the crypto intrinsics. This means contracts that were using `capi_checksum256` to calculate a SHA256 hash using the `sha256` intrinsic which was then stored in a table would have the byte sequence in the order of MSB to LSB. If the contract wished to upgrade the type of that table row to a `eosio::key256` in the future, its deserialization implementation would mix up the bytes causing all kinds of problems.
Furthermore, the builtin `checksum256` ABI type …
> Various modifications

- libraries/eosiolib/CMakeLists.txt
- libraries/eosiolib/crypto.cpp
- libraries/eosiolib/crypto.hpp
- libraries/eosiolib/datastream.hpp
- libraries/eosiolib/fixed_bytes.hpp
- libraries/eosiolib/multi_index.hpp
- libraries/eosiolib/permission.hpp
- libraries/eosiolib/privileged.hpp
- libraries/eosiolib/public_key.hpp
- tools/include/eosio/gen.hpp
This PR makes changes to the additions in PR #236.
Specifically, this PR includes the following changes:
- To reduce confusion, it renames the type aliases to `eosio::fixed_bytes` introduced in PR #236 as follows:
+ `eosio::digest160` is now `eosio::checksum160`
+ `eosio::digest256` is now `eosio::checksum256`
+ `eosio::digest512` is now `eosio::checksum512`
- Adds a C++ type `eosio::signature` (with serialization/deserialization support) to be used instead of the C struct `capi_signature`.
- Modifies the `eosio::recover_key` and `eosio::assert_recover_key` C++ functions introduced in PR #236 which simply wrap the functionality of the corresponding C intrinsics so that they now take the new `eosio::signature` type as an argument.
> rename digest to checksum; add eosio::signature

- libraries/eosiolib/name.hpp
- modules/EosioWasmToolchain.cmake.in
```
set_target_properties( ${TARGET}.wasm PROPERTIES LINKER_LANGUAGE C )
```
Cause my cmake generate -lm -lstdc++
cmake version 3.10.2
```
return eosio::name{std::string_view{eosio::detail::to_const_char_arr<Str...>::value, sizeof...(Str)}};
```
Does not execute in compile time!
> Force execute compile time

- .buildkite/pipeline.yml
- docker/dev/Dockerfile
- scripts/generate_bottle.sh
- scripts/generate_deb.sh
- scripts/generate_rpm.sh
- scripts/generate_tarball.sh
The pipeline builds the supported OSes (Mac High Sierra and Mojave, Ubuntu 18.04, Fedora, CentOS, and Amazon Linux) and creates packages as artifacts for each (where applicable).
> Added a buildkite pipeline

- libraries/eosiolib/print.hpp
The last patch to allow printing of any integer type, created a new issue with using lvalues.  This PR resolves this.
> Fixes to print for lvalue references

- scripts/generate_deb.sh
- scripts/generate_package.sh.in
- scripts/generate_rpm.sh
In order to properly report status in Buildkite we need the return code of `rpmbuild` and `dpkg-deb` to be bubbled up to `generate_package.sh`.
> Fix return codes of build scripts so that buildkite can fail properly

- .buildkite/pipeline.yml
I have configured the Buildkite pipeline to run unit tests on each platform after the builds but before the package creation. Unit testing (ctest) already exists in the repo and has not been updated. All changes have been made in the Buildkite configuration file here:
/.buildkite/pipeline.yml
I have also added some comments to make the file easier to navigate, and have made the build step labels slightly more descriptive and uniformly stylized.
Currently all unit test build steps fail, and this is expected. All macintosh builds fail with file/folder not found errors if and only if the scheduler runs the unit tests on a different virtual machine than the build. This is due to absolute paths being used for the configuration of CMAKE_BUILD_DIR where relative paths should be used, and Nathan …
> Added Unit Tests to Buildkite Pipeline

- tools/init/eosio-init.cpp
Fixes #369.
Project name given by the option `-project` of `eosio-init` is used as a class name of contract. It should be a valid c++ identifier.
> Throw exception when creating project with invalid identifier

- tools/abigen/eosio-abigen.cpp.in
The abigen adds a comment to the generated ABI file. This comment includes a timestamp information at which time the ABI file was generated. This is problematic when trying to reproduce an exact identical ABI file since the timestamp will make the file looks different.
This PR removes the actual timestamp information from the comment and only keep the static text instead.
By not having the timestamp, someone can checkout a particular tag, perform the build step and validate that the sha256 of the ABI file has not changed.
> Removes the timestamp part of the abigen comment

- libraries/eosiolib/fixed_bytes.hpp
Problematic Code:
```
template<typename Word, size_t NumWords,
typename Enable = typename std::enable_if<std::is_integral<Word>::value &&
!std::is_same<Word, bool>::value &&
sizeof(Word) < sizeof(word_t)>::type >
```
The Fix: 
```
template<typename Word, size_t NumWords,
typename Enable = typename std::enable_if<std::is_integral<Word>::value &&
!std::is_same<Word, bool>::value &&
std::less( sizeof(Word), sizeof(word_t))>::type >
```
Problem occurred in two places.
Doxygen did not interpret the `<` operator in the `sizeof(Word) < sizeof(word_t)>::type` as less than.
This only seems to affect `<`, until issue is addressed in Doxygen, should consider a temporary convention. 
Doxygen now works as expected for `fixed_bytes.hpp`
Resolves #382
> Help Doxygen interpret otherwise valid C++ syntax

- libraries/eosiolib/core/eosio/rope.hpp
Emulate an unlimited stack to prevent stack overflow
> rope::c_str(): don't recurse

- libraries/eosiolib/time.hpp
- Deprecate error prone `time_point::operator+` and `time_point_sec::operator+=` and `time_point_sec::operator-=`
- today@1pm + today@1pm == year4039  <= clearly not what is expected
- today@5pm - today@4pm == year1970 <= clearly not what is expected
> Deprecate error prone + += -= operators

- libraries/eosiolib/contracts/eosio/transaction.hpp
This PR fixes #486 duplicated symbol linker error for function `eosio::send_deferred`.
> Fix duplicated symbol error

- tools/cc/eosio-cc.cpp.in
- tools/cc/eosio-cpp.cpp.in
Because CDT 1.6.x uses system_temp_directory to build source file, so header file in the original path of source file cannot be found, unless explicit `-I./` is given.
For example, project tree is like the next:
```
test
- test.cpp
- test.hpp
```
`test.cpp` includes `test.hpp` directly.
``` c++
#include "test.hpp"
....
```
In case of this, `eosio-cpp` 1.6.x fails to compile `test.cpp`. This patch adds `-I + (source file path)` to make `eosio-cpp` find the header file correctly.
> Include source path for header directory by default

- libraries/eosiolib/contracts/eosio/action.hpp
`context_free_actions` should not contain permission_level, but action_wrapper always requires permission_level to instantiate it. This patch allows action_wrapper without permission_level to wrap context_free_action.
N/A
N/A
> Allow to instantiate action_wrapper without permission_level

- libraries/eosiolib/contracts/eosio/action.hpp
Fix a typo and remove unnecessary part from `action_wrapper` documentation
N/A
N/A
> Fix typo and error in action_wrapper documentation

- tools/include/compiler_options.hpp.in
Cross reference to the change in repository `EOSIO/lld` [#6](https://github.com/EOSIO/lld/pull/6).
The default behavior of `eosio-ld` is to automatically generate an `.abi` file for the user. With the additional of this new flag, `-fno-abigen`, the user can now specify whether or not an `.abi` should be generated by the linker.
> New flag: `-fno-abigen`

- scripts/eosiocdt_build.sh
Build script divides `free memory` by 4 GB to get the number of JOBS when executing `make`, but the amount of free memory is usually very small. In my machine, it executes `make -j1`, even though it has hexa-core CPU (i7-8700) and 16 GB memory. IMHO, the dividend might need to be `available memory` instead of free. If there is another rationale that I miss, feel free to reject this.
> Use the amount of available memory to get the number of JOBS

- modules/EosioWasmToolchain.cmake.in
- scripts/generate_tarball.sh
Install `eosio-ar` to `bin` to make it available to build static library.
> Add `eosio-ar` support in toolchain cmake to build static libarary

- tools/include/eosio/whereami/linux.hpp
Fix build warning because of redefinition of `__STDC_FORMAT_MACROS`
> Fix redefinition warning __STDC_FORMAT_MACROS

- scripts/eosiocdt_build_amazon.sh
- scripts/eosiocdt_build_fedora.sh
- scripts/eosiocdt_build_ubuntu.sh
Some build scripts missed `break;;` in their script, so it's not possible to pass updating repositories for build dependencies. This patch adds missing line, so makes scripts available to build without updating repos.
> Add missing `break` in build script to pass repo update

- libraries/eosiolib/asset.hpp
- libraries/eosiolib/core/eosio/asset.hpp
* fix double minus sign when the amount is negative
* remove redundant decimal dot when fractional part doesn't exist
> Fix errors in eosio::asset::to_string()

- libraries/eosiolib/core/eosio/symbol.hpp
- libraries/native/native/eosio/tester.hpp
- libraries/native/tester.hpp
- tests/unit/symbol_tests.cpp
- Fixed bug in `CHECK_ASSERT` and `CHECK_PRINT` macros which could undo a prior recording of a failure.
- Fixed bug in `symbol::print` which used the wrong function to print the symbol code. (This bug was exposed from a test failure in `symbol_tests` after the `CHECK_PRINT` function was fixed.)
- Corrected the `symbol_tests` unit test to use the proper expected print messages.
> More fixes to native tester macros - 1.6.x

- libraries/eosiolib/asset.hpp
- libraries/eosiolib/core/eosio/asset.hpp
- libraries/eosiolib/core/eosio/name.hpp
- libraries/eosiolib/core/eosio/powers.hpp
- libraries/eosiolib/core/eosio/symbol.hpp
- libraries/eosiolib/eosiolib.cpp
- libraries/eosiolib/name.hpp
- libraries/eosiolib/symbol.hpp
- tests/unit/asset_tests.cpp
Changes in this PR:
- Added `asset::write_as_string` member function which allows for efficiently writing out the asset into a character buffer. (`asset::to_string` and `asset::print` have been reimplemented to now use this new `asset::write_as_string` function.)
- Modifed all `write_as_string` member functions (in `name`, `symbol_code`, and `asset`) to take an optional `dry_run` parameter and to be less strict with their preconditions. 
-  Fixed the few test cases in `asset_tests` that were comparing the string representation of specific assets with negative quantities to incorrect expected values. (Similar to #557).
- Added additional test cases to `asset_tests`.
This PR acts as an alternative to #650.
> Reimplement asset::to_string() and related functions - 1.6.x

- libraries/eosiolib/contracts/eosio/multi_index.hpp
- libraries/eosiolib/multi_index.hpp
Fixes inaccurate documentation of `multi_index::upper_bound`. Ports #580 and #662 to the release/1.6.x branch.
> Fix upper_bound documentation - 1.6.x

- libraries/eosiolib/contracts/eosio/multi_index.hpp
Fixes inaccurate documentation of `multi_index::upper_bound`. Applies fixes of #580 to the other copy of `multi_index.hpp` in eosiolib.
> Fix upper_bound documentation - develop

- libraries/eosiolib/asset.hpp
- libraries/eosiolib/core/eosio/asset.hpp
- libraries/eosiolib/core/eosio/name.hpp
- libraries/eosiolib/core/eosio/powers.hpp
- libraries/eosiolib/core/eosio/symbol.hpp
- libraries/eosiolib/eosiolib.cpp
- libraries/eosiolib/name.hpp
- libraries/eosiolib/symbol.hpp
- tests/unit/asset_tests.cpp
Changes in this PR:
- Added `asset::write_as_string` member function which allows for efficiently writing out the asset into a character buffer. (`asset::to_string` and `asset::print` have been reimplemented to now use this new `asset::write_as_string` function.)
- Modified all `write_as_string` member functions (in `name`, `symbol_code`, and `asset`) to take an optional `dry_run` parameter and to be less strict with their preconditions. 
- Added additional test cases to `asset_tests`.
> Reimplement asset::to_string() and related functions - develop

- libraries/eosiolib/capi/eosio/types.h
- libraries/eosiolib/core/eosio/crypto.hpp
- libraries/eosiolib/core/eosio/datastream.hpp
- libraries/eosiolib/types.h
- tests/unit/crypto_tests.cpp
- tests/unit/datastream_tests.cpp
Added support for WebAuthN keys and signatures to the c++ wrapper types.  Deprecated the fixed size `capi_` types for both signature and public_key as they are no longer sufficient to represent the potentially variable-sized keys in the future
The c++ types for `eosio::signature` and `eosio::public_key` are different.  Before these were simple structs with public fields for the "which" type of public key and underlying buffer of bytes, these are now variants of either an `std::array<char, 65>` or a `webauthn_signature` and `std::array<char, 33>` or a `webauthn_public_key` respectively.
The c++ types for `eosio::signature` and `eosio::public_key` have become significantly more complex to handle the unexposed details of what those data types really were.  This resulted in shifting the types …
> WebAuthN Support

- libraries/eosiolib/capi/eosio/privileged.h
- libraries/eosiolib/capi/eosio/system.h
- libraries/eosiolib/contracts/eosio/privileged.hpp
- libraries/eosiolib/contracts/eosio/system.hpp
- libraries/eosiolib/eosiolib.cpp
- libraries/native/intrinsics.cpp
- libraries/native/native/eosio/intrinsics_def.hpp
Added support for the `preactivate_feature`, `is_feature_activated`, and `get_sender` intrinsics.
Temporarily moved the implementation of the new `set_proposed_producers` overload introduced in PR #570 from the `eosiolib.cpp` file to an inline function defined in the `privileged.hpp` header file. This is to workaround a issue in CDT which brings in all imported intrinsics used within an object file (e.g. `eosiolib.cpp.obj`) that is linked into the compiled WebAssembly file, even if those intrinsics aren't actually used in any of the contract code. This means that prior to this change, a contract designed to work with EOSIO v1.8.x only would likely inadvertently bring in a dependency to the `set_proposed_producers_ex` intrinsic (a v2.0.x and above feature) within the compiled WASM and thus …
> add support for preactivate_feature, is_feature_activated, and get_sender intrinsics; move definition of new set_proposed_producers function 

- libraries/eosiolib/crypto.cpp
The *_recover_key wrapper functions presumed a fixed size serialization buffer which no longer holds now that sigs and pubkeys can be variable sized
related to #659
> Fix recover key wrappers in light of variable-sized keys and sigs

- libraries/eosiolib/core/eosio/crypto.hpp
Add remaining comparison operators to `eosio::webauthn_public_key`.
> Add remaining comparison operators to eosio::webauthn_public_key

- libraries/eosiolib/contracts/eosio/action.hpp
> Add missing operator < for permission_level

- tools/include/eosio/abigen.hpp
Fix #601.
abigen removes unused defs from abi json, but when struct base type is aliased type (typedef, using), its type is excluded from json generation unexpectedly.
To avoid merge conflict, changes by #604 are included. If this PR is merged, #604 isn't necessary.
> Fix missing ABI when struct base is typedef'ed

- tools/include/eosio/abigen.hpp
Fix #558. 
When passed parameter of clang::QualType is not clang::ElaboratedType, segfault occurs during ABI generation.
> Fix segfault during ABI generation for tuple

- tools/include/eosio/abigen.hpp
Fix #602.
When aliased type (typedef, using) is used as a template argument of variant, its typedef is excluded from json output unexpectedly.
> Fix missing ABI when aliased type used in variant

- tools/include/eosio/gen.hpp
Fix #600.
When typedef is nested in other namespace, `clang::ElaboratedType` is passed to `get_type_alias` instead of `clang::TypedefType`. When dynamic cast to clang::TypedefType fails, try casting to
ElaboratedType once mroe to avoid build fail by segfault.
> Fix segfault when using nested typedef

- tools/include/eosio/abigen.hpp
Fix #527. 
`add_type` calls itself recursively to add all types it refers to. If user-defined types refer to each other or themselves, it causes stack overflow by cycle.
> Fix stack overflow caused by recursive add_type 

- libraries/eosiolib/eosiolib.cpp
get_active_producers from wasm_interface treats the second argument as size of buffer in bytes, but get_active_producers from eosio.cdt puts active_prods.size() as a second argument.
This leads to corrupted active_prods where only 21 bytes of 8*21 are filled.
> Fix get_active_producers

- libraries/eosiolib/chain.h
- libraries/eosiolib/eosiolib.cpp
- tools/include/compiler_options.hpp.in
- tools/include/eosio/abigen.hpp
- tools/include/eosio/gen.hpp
Cherry-picked fixes that are in develop.
> Cherry picked fixes release 1.6.x

- libraries/eosiolib/eosiolib.cpp
- libraries/libc++/CMakeLists.txt
- tools/cc/eosio-cpp.cpp.in
- tools/include/compiler_options.hpp.in
- tools/include/eosio/abigen.hpp
Cherry-pick fixes from release/1.6.x to develop
> Cherry pick fixes develop

- libraries/eosiolib/contracts/eosio/producer_schedule.hpp
- libraries/eosiolib/eosiolib.cpp
Add `is_valid` member function to `block_signing_authority_v0` which allows the caller to determine whether the block signing authority is valid, or:
- does not have repeating keys;
- the sum of the weights is at least equal to the threshold;
- and, the threshold is not 0.
It does not validate whether the keys are valid.
These are the same validations that are done on the EOSIO native side for each of the block signing authorities submitted via `set_proposed_producers_ex` when using the new format (at least after EOSIO/eos#8021 has been merged in).
> Add is_valid member function to block_signing_authority_v0

- .cicd/pipeline.yml
To meet package naming conventions the package should contain el7 instead of centos
> Fix centos package name

- .cicd/tests.sh
Reviewing PR#713 in eosio.cdt revealed that we are currently not uploading test results in eosio.cdt and eosio.contract test steps. The test metrics step is falling back to parsing the Buildkite log, which is not ideal.
Fixed issue where test steps did not upload artifacts correctly.
- Test metric step now refers to test-results.xml as generated by ctest instead of defaulting to parsing log output.
> [develop] Test metrics fix

- .cicd/tests.sh
Reviewing PR#713 in eosio.cdt revealed that we are currently not uploading test results in eosio.cdt and eosio.contract test steps. The test metrics step is falling back to parsing the Buildkite log, which is not ideal.
Fixed issue where test steps did not upload artifacts correctly.
- Test metric step now refers to test-results.xml as generated by ctest instead of defaulting to parsing log output.
> [1.7.x] Test metrics fix

- .cicd/tests.sh
Reviewing PR#713 in eosio.cdt revealed that we are currently not uploading test results in eosio.cdt and eosio.contract test steps. The test metrics step is falling back to parsing the Buildkite log, which is not ideal.
Fixed issue where test steps did not upload artifacts correctly.
- Test metric step now refers to test-results.xml as generated by ctest instead of defaulting to parsing log output.
> [1.6.x] Test metrics fix

- libraries/libc/CMakeLists.txt
- tools/include/compiler_options.hpp.in
This fixes the divergence between the libcxx submodule and libcxx@eosio.  OSX is handled by #undefing ``__APPLE__``, to disable OSX specific functionality which is not supported by CDT.
> Fix osx builds

- docs/06_how-to-guides/02_multi-index/how-to-define-a-primary-index.md
- docs/06_how-to-guides/02_multi-index/how-to-define-a-secondary-index.md
- docs/06_how-to-guides/02_multi-index/how-to-define-a-singleton.md
- docs/06_how-to-guides/02_multi-index/how-to-delete-data-from-a-multi-index-table.md
- docs/06_how-to-guides/02_multi-index/how-to-insert-data-into-a-multi-index-table.md
- docs/06_how-to-guides/02_multi-index/how-to-instantiate-a-multi-index-table.md
- docs/06_how-to-guides/02_multi-index/how-to-iterate-and-retrieve-a-multi_index-table-based-on-secondary-index.md
- docs/06_how-to-guides/02_multi-index/how-to-iterate-and-retrieve-a-multi_index-table.md
- docs/06_how-to-guides/02_multi-index/how-to-modify-data-in-a-multi-index-table.md
- docs/09_tutorials/02_abi-variants.md
Fixes callouts in the docs in `release/1.7.x`. Was using `Info` as opposed to the required lowercase variant `info`. Was not rendering, as seen below:
After correction:
> [release/1.7.x] Fix callouts in docs

- libraries/eosiolib/capi/eosio/action.h
- libraries/eosiolib/contracts/eosio/action.hpp
- libraries/native/intrinsics.cpp
- libraries/native/native/eosio/intrinsics_def.hpp
- tests/unit/test_contracts/capi/action.c
- Adds new intrinsic `set_action_return_value` enabled by https://github.com/EOSIO/eos/pull/8327
```
/**
* Set the action return value which will be included in the action_receipt
* @brief Set the action return value
* @param return_value - serialized return value
* @param size - size of serialized return value in bytes
* @pre `return_value` is a valid pointer to an array at least `size` bytes long
*/
```
> Add new intrinsic set_action_return_value

- CMakeLists.txt
This removes unnecessary installation from CMakeLists.txt. `eosio_cmake_install_and_symlink` in modules/InstallCDT.cmake will handle this.
> Remove redundant install from CMakeLists.txt

- libraries/eosiolib/contracts/eosio/action.hpp
The CAPI for action return value takes a non-const char*, so it's a compile error to pass a const char* from a const vector<> here
> don't use a const vector<> for action return value pack()

- libraries/eosiolib/core/eosio/symbol.hpp
The current definition will produce an ABI for extended_symbol that will fail in abi_serializer.
> fix for extended_symbol 1.7.x

- libraries/eosiolib/binary_extension.hpp
- libraries/eosiolib/core/eosio/binary_extension.hpp
Allow for the type `binary_extension` to build if the given parameterized type only has an explicit default constructor.
> release/1.6.x `binary_extension` and explicit default constructors fix

- libraries/eosiolib/core/eosio/binary_extension.hpp
Allow for the type `binary_extension` to build if the given parameterized type only has an explicit default constructor.
> release/1.7.x `binary_extension` and explicit default constructors fix

- libraries/eosiolib/core/eosio/binary_extension.hpp
Allow for the type `binary_extension` to build if the given parameterized type only has an explicit default constructor.
> develop `binary_extension` and explicit default constructors fix

- .github/workflows/main.yml
This is a quick change to Actions runs when community PRs are submitted:
- Remove now unnecessary job that executed before build/test steps occurred in Github Actions.
- This step was required due to a bug in Actions where if all workflow steps were skipped, such as when org based PRs are executed, the build would be marked as failed.
- The behavior now shows status as expected, where the steps based in the org do now show up at all.
See:
[Actions](https://github.com/EOSIO/eosio.cdt/actions/runs/44382821) | Actions run from #822 showing the same functionality as before.
[Actions](https://github.com/EOSIO/eosio.cdt/actions/runs/44543019) | Actions run created from this PR where all steps are skipped as expected. No checks from Actions show as failed in this PR.
> [1.6.x] Community PR tweaks.

- .github/workflows/main.yml
This is a quick change to Actions runs when community PRs are submitted:
- Remove now unnecessary job that executed before build/test steps occurred in Github Actions.
- This step was required due to a bug in Actions where if all workflow steps were skipped, such as when org based PRs are executed, the build would be marked as failed.
- The behavior now shows status as expected, where the steps based in the org do now show up at all.
See:
[Actions](https://github.com/EOSIO/eosio.cdt/actions/runs/44382821) | Actions run from #822 showing the same functionality as before.
[Actions](https://github.com/EOSIO/eosio.cdt/actions/runs/44542651) | Actions run created from this PR where all steps are skipped as expected. No checks from Actions show as failed in this PR.
> [1.7.x] Community PR tweaks.

- .cicd/submodule-regression-checker.sh
- .github/workflows/main.yml
Fixed an issue regarding checkouts when rerunning a failed forked PR:
- Removed use of Actions checkout plugin for several reasons:
- Version 1 of the plugin does not handle the race condition between the "merge commit" being created in Github and trying to checkout this commit.
- Version 2 of the plugin addressed the above issue... but does not allow submodules to be checked out automatically.
- We can use v2 of the plugin and manually checkout submodules... but v2 of the plugin does not checkout the full history of the repo, required for the submodule regression check.
- Actions-based environment variables are set incorrectly on PR reruns of forked repositories...
- Replaced Actions plugin with our own checkout steps:
- Clone the full repo.
- Checkout the specific ref tied to the pull …
> [develop] Actions rerun fixes.

- .cicd/submodule-regression-checker.sh
- .github/workflows/main.yml
Fixed an issue regarding checkouts when rerunning a failed forked PR:
- Removed use of Actions checkout plugin for several reasons:
- Version 1 of the plugin does not handle the race condition between the "merge commit" being created in Github and trying to checkout this commit.
- Version 2 of the plugin addressed the above issue... but does not allow submodules to be checked out automatically.
- We can use v2 of the plugin and manually checkout submodules... but v2 of the plugin does not checkout the full history of the repo, required for the submodule regression check.
- Actions-based environment variables are set incorrectly on PR reruns of forked repositories...
- Replaced Actions plugin with our own checkout steps:
- Clone the full repo.
- Checkout the specific ref tied to the pull …
> [1.7.x] Actions rerun fixes.

- .cicd/submodule-regression-checker.sh
- .github/workflows/main.yml
Fixed an issue regarding checkouts when rerunning a failed forked PR:
- Removed use of Actions checkout plugin for several reasons:
- Version 1 of the plugin does not handle the race condition between the "merge commit" being created in Github and trying to checkout this commit.
- Version 2 of the plugin addressed the above issue... but does not allow submodules to be checked out automatically.
- We can use v2 of the plugin and manually checkout submodules... but v2 of the plugin does not checkout the full history of the repo, required for the submodule regression check.
- Actions-based environment variables are set incorrectly on PR reruns of forked repositories...
- Replaced Actions plugin with our own checkout steps:
- Clone the full repo.
- Checkout the specific ref tied to the pull …
> [1.6.x] Actions rerun fixes.

- libraries/eosiolib/core/eosio/string.hpp
This PR fixes the duplicated symbol linker error when including `eosio::string` in more then 1 source file.
> Fix (eosio::string): Add inline specifier to friend functions

- docs/06_how-to-guides/02_multi-index/how-to-instantiate-a-multi-index-table.md
- libraries/boost/include/boost/hana/fwd/type.hpp
- libraries/boost/include/boost/move/algo/adaptive_sort.hpp
- libraries/eosiolib/core/eosio/time.hpp
- tools/external/wabt/src/wast-parser.h
resolves #815
fix typos "and and" -> "and"
> [docs] fixes typos "and and" -> "and"

- README.md
fixes #846
remove preceding '$' chars from shell commands
> [Docs] 1.7.x - correct README.md - remove preceding '$' chars from shell commands

- README.md
fixes #846 
remove preceding '$' chars from shell commands
> [Docs] develop: correct README.md - remove preceding '$' chars from shell commands

- libraries/CMakeLists.txt
- modules/EosioWasmToolchain.cmake.in
- tests/CMakeLists.txt
- tools/cc/eosio-cpp.cpp.in
- tools/include/compiler_options.hpp.in
- tools/include/eosio/abigen.hpp
- tools/include/eosio/gen.hpp
Add commandline option `-no-missing-ricardian-clause` to `eosio-cpp`.  Apply option to build process, suppressing warnings generated while building the contract version of libc++ and the tests.  Includes some whitespace cleanup.
Commandline option `-no-missing-ricardian-clause` added to `eosio-cpp`.  Defaulting to false, if enabled, it suppresses warnings concerning missing Ricardian clauses on contracts and contract actions, including warnings generated when there is also no independent Ricardian clause file.  Any copy of the `-help` output of `eosio-cpp` should be refreshed to show the new option.
> Add commandline option -no-missing-ricardian-clause.

- scripts/eosiocdt_build_darwin.sh
Building on a fresh macOS installation with no dependencies failed with a bash error:  `line 122: [: =: unary operator expected`.
> Building on macOS with no dependencies installed did not work.

- docs/03_command-reference/eosio-init.md
Resolves #883, correction for `eosio-init` example.
> [docs] Correction for eosio-init example in develop branch.

- tools/external/wabt/CMakeLists.txt
Turn off building wabt with `-Werror`. This is too hostile IMO (we removed it in EOSIO too) and it's causing cdt to fail building with gcc10. Another option could consider is disabling only the warnings that are causing gcc10 failures.
> turn off Werror for wabt

- .cicd/pipeline.yml
- Bumped Catalina CICD builders to 10.15.5.
- Bumped max disk size to 80GB.
- Updated Anka plugin to latest version.
- Toolchain tests were not executing on Catalina. Added this into pipeline.
> [develop] Anka/Catalina CICD version bumps

- libraries/eosiolib/contracts/eosio/multi_index.hpp
[docs] fix annotation for get_code() and get_scope()
fixes #898
> [docs] fix annotation for get_code() and get_scope()

- libraries/eosiolib/contracts/eosio/multi_index.hpp
[docs] release/1.7.x  fix annotation for get_code() and get_scope()
fixes #898
> [docs] release/1.7.x  fix annotation for get_code() and get_scope()

- docs/05_best-practices/05_securing_your_contract.md
- docs/05_best-practices/09_deferred_transactions.md
- docs/06_how-to-guides/05_authorization/how_to_restrict_access_to_an_action_by_user.md
- libraries/eosiolib/contracts/eosio/multi_index.hpp
- libraries/eosiolib/core/eosio/datastream.hpp
fixes #905 as of eosio 2.0-rc1 deferred transactions are deprecated
fixes #865 Introduce the eosio::check(eosio::has_auth(...))
fixes #866 Corrections are needed on the best practices, securing your contract
fixes #871 "for the Storage usage of the updated row" lowercase inconsistent
fixes #877 delete duplicated lines in datastream class annotations
> [Docs] content updates and fixes

- docs/05_best-practices/05_securing_your_contract.md
- docs/05_best-practices/09_deferred_transactions.md
- docs/06_how-to-guides/05_authorization/how_to_restrict_access_to_an_action_by_user.md
- libraries/eosiolib/contracts/eosio/multi_index.hpp
- libraries/eosiolib/core/eosio/datastream.hpp
Backport of PR #906 to 1.7
fixes #905 as of eosio 2.0-rc1 deferred transactions are deprecated
fixes #865 Introduce the eosio::check(eosio::has_auth(...))
fixes #866 Corrections are needed on the best practices, securing your contract
fixes #871 "for the Storage usage of the updated row" lowercase inconsistent
fixes #877 delete duplicated lines in datastream class annotations
> [docs] 1.7.x content and annotations updates

- .cicd/pipeline.yml
- libraries/eosiolib/tester/tester.cpp
Passing a const argument to build_history_result causes it always to choose the error overload.
> Fix test_chain::get_history

- .cicd/pipeline.yml
- tools/include/compiler_options.hpp.in
In LLVM9, special handling was added for `rodata` when creating the data segments. Before that, it was not handled and therefore was always not merged. This restores that behaviour to prevent having segments that are too large.
An alternative would be to remove the handling inside lld, but this feels like the less intrusive solution and clearly communicates the behaviour we want.
> Don't default to merging data sections, it can blow out nodeos limits

- tools/include/eosio/gen.hpp
> Convert vector<uint8_t> to bytes in ABI

- .cicd/pipeline.yml
- docs.json
- libraries/eosiolib/asset.hpp
- libraries/eosiolib/core/eosio/asset.hpp
- libraries/eosiolib/core/eosio/symbol.hpp
- libraries/eosiolib/symbol.hpp
a bunch of broken links were generated in reference documentation for cdt 1.6 because the docs.json
also a bit of improvements for annotations were done
addressing DEVREL-436
> [docs] adding missing docs.json and improve annotations

- libraries/eosiolib/contracts/eosio/key_value.hpp
- tests/unit/test_contracts/kv_make_key_tests.cpp
- tests/unit/test_contracts/kv_multiple_indices_tests.cpp
- tests/unit/test_contracts/kv_single_index_tests.cpp
- tests/unit/test_contracts/kv_variant_tests.cpp
Allow application developers flexibility to choose who pays for resources. 
`kv_table::put()` has an additional optional parameter `payer`
> add payer support for kv table

- tools/include/eosio/codegen.hpp
Handle action parameters that have a template type that translates to `_Bool` during codegen.
Fixes #862.
>  Fix problem with action parameters with a template type of bool

- docs/06_how-to-guides/06_key_value/01_key_value_examples.md
- libraries/eosiolib/contracts/eosio/key_value.hpp
- tests/unit/test_contracts/kv_make_key_tests.cpp
- tests/unit/test_contracts/kv_multiple_indices_tests.cpp
- tests/unit/test_contracts/kv_single_index_tests.cpp
- tests/unit/test_contracts/kv_variant_tests.cpp
Currently, the key value API in EOSIO.CDT has the prefix 'kv_' used almost everywhere.  This is problematic in a couple of ways, one is that the user has to type 'kv_' a lot and it is a bit reminiscent of C style "namespacing".  So, we should simply add the namespace 'kv' over these data types.  These names will also need to be updated in tests, abigen, and docs.
It also, appears that 'kv_singleton' either made its way back in or it fully wasn't removed in any of the previous PRs.  This data type can be massive foot gun for developers and it is difficult to concisely express the semantics of it.  The remedy is to just remove the data type 'kv_singleton' and any usages from the tests.
> Final CDT key value cleanup

- libraries/eosiolib/contracts/eosio/multi_index.hpp
Add support for passing reference to secondary index. Currently, primary index supports passing both iterator and object reference, but secondary indices only supports the case of iterator.
> Add support for passing reference to secondary index

- .cicd/build-integration.sh
- .cicd/integration-tests.sh
- .cicd/pipeline.yml
Depends on #965 to pass integration tests
> Add integration tests to CI

- docs/09_tutorials/02_abi-variants.md
Corrected how "variants" is quoted in the final section of the doc.
> Quoting correction

- tools/external/wabt/src/tools/postpass.cc
- tools/include/compiler_options.hpp.in
- tools/ld/eosio-ld.cpp.in
- tools/toolchain-tester/main.py
- tools/toolchain-tester/tests.py
- tools/toolchain-tester/testsuite.py
This allows creating contracts that can be used with profiler (https://github.com/EOSIO/eos/pull/9541) to get human readable names for functions.
Note that the contracts may be too large to put on chain.  Running `wasm-strip` will remove the debug names section while still allowing the unstripped wasm to be used with off-chain tooling.
> Make the contracts generated with --allow-names usable.

- examples/kv_addr_book/include/kv_addr_book.hpp
According to Steven, ABI generator has a bug to generate types of indices in KV tables: https://github.com/EOSIO/eosio.cdt/blob/develop/tools/include/eosio/abigen.hpp#L311-L323. A workaround is to use unqualified names,  like name  instead of eosio::name.
> workround of abi generator bug for key types

- .cicd/build.sh
- .cicd/integration-tests.sh
- .cicd/pipeline.yml
The Ubuntu 18.04 build was incorrectly building a tag name to use for it's build based on the contract builder image being used:
- Set back to using default `ubuntu-18.04` as `IMAGE_TAG`.
- Let's us ensure the correct container exists for unit and toolchain tests as well as community PRs.
- Check if Buildkite and using Ubuntu 18.04 for build step.
- If so, explicitly use the contract builder container.
- Same for integration test steps.
> [develop] Fix U18 develop build.

- libraries/eosiolib/capi/eosio/privileged.h
- libraries/eosiolib/contracts/eosio/privileged.hpp
- libraries/eosiolib/eosiolib.cpp
- libraries/native/intrinsics.cpp
- libraries/native/native/eosio/intrinsics_def.hpp
- tests/unit/test_contracts/kv_bios/kv_bios.cpp
This PR is the CDT part of the task that adding support for setting KV Parameters to `eosio.system` contract and `eosio.bios` contract https://github.com/EOSIO/eosio.contracts/pull/532. It adds `set_kv_parameters` and all necessary definitions. The changes were tested using the tests introduced in https://github.com/EOSIO/eosio.contracts/pull/532.
> Enable support of setkvparams in CDT

- libraries/eosiolib/contracts/eosio/key_value.hpp
Added bool operator to KV table iterator so that developers can easily check if the iterator exists by using an `if (itr) {}` statement.
**Select ONE**
> add KV Table iterator bool operator

- tools/cc/eosio-cpp.cpp.in
- tools/include/compiler_options.hpp.in
- tools/include/eosio/codegen.hpp
- tools/include/eosio/utils.hpp
- Fix dependency file generation (-MD/-MMD) to hold the original source and not the generated temporary file.
- Make temporary filenames unique to avoid races in parallel builds.
> Fix some issues when building EOSIO contracts

- libraries/eosiolib/core/eosio/print.hpp
This PR adds more restrictive conditions for matching the general template `print` overload that is meant to work with classes (i.e. meant to call a `print` member function of the class). It now only enables the overload if the class has a member function called `print` which can take no arguments. To continue supporting `std::string` (which was previously added via `if constexpr` within this general template overload for some reason), a new explicit overload of the `print` function has been added. In addition, another explicit overload of the `print` function has been added to also support `std::string_view`.
@larryk85 Please consider including this patch into the `develop` branch as well.
> Improvements to print overloads and add support for printing std::string_view

- docs/06_how-to-guides/30_key-value-api/10_how-to-use-kv-table.md
- docs/06_how-to-guides/30_key-value-api/20_how-to-create-indexes.md
- docs/06_how-to-guides/30_key-value-api/30_how-to-upsert-into-table.md
- docs/06_how-to-guides/30_key-value-api/40_how-to-delete-from-table.md
- docs/06_how-to-guides/30_key-value-api/50_how-to-iterate.md
- docs/06_how-to-guides/30_key-value-api/60_how-to-check-a-record.md
- docs/06_how-to-guides/30_key-value-api/70_how-to-find-in-table.md
- docs/06_how-to-guides/30_key-value-api/80_how-to-query-range-in-table.md
- docs/06_how-to-guides/30_key-value-api/90_how-to-allow-users-to-pay.md
- docs/06_how-to-guides/30_key-value-api/index.md
- examples/kv_addr_book/include/kv_addr_book.hpp
- examples/kv_addr_book/src/kv_addr_book.cpp
- examples/kv_map/CMakeLists.txt
- examples/kv_map/README.txt
- examples/kv_map/include/kv_map.hpp
- examples/kv_map/ricardian/kv_example.contracts.md
- examples/kv_map/src/CMakeLists.txt
- examples/kv_map/src/kv_map.cpp
1. get rid of the eosio::non_unique from kv_addr_book example
2. clean the kv table related content files (.md)
3. add kv_map example
4. cosmetic clean up (unnecessary comments, dead code, back-ticks vs single-ticks, etc.)
> [docs] get rid of the eosio::non_unique from kv_addr_book example

- libraries/eosiolib/contracts/eosio/privileged.hpp
- libraries/eosiolib/eosiolib.cpp
Implementation of set_kv_parameters was placed in libraries/eosiolib/eosiolib.cpp. This caused the problem that set_kv_parameters_packed was included in every contract, and in turn caused unresolved symbol error when deploying non-bios or non-systm contracts. The fix is to move to to eosiolib/contracts/eosio/privileged.hpp.
> Fix unresolved set_kv_parameters_packed problem

- .cicd/pipeline.yml
We've had reports of Mac build failures in overnight builds. This appears to be caused by Homebrew reporting an error when attempting to install a package that already exists, but is an older version. This change fixes this by executing `brew upgrade` before installing our dependencies. This should catch issues with updates to packages that already exist on the VMs, such as `wget`.
> [1.8.x] Fix brew when installing existing package

- .cicd/pipeline.yml
We've had reports of Mac build failures in overnight builds. This appears to be caused by Homebrew reporting an error when attempting to install a package that already exists, but is an older version. This change fixes this by executing `brew upgrade` before installing our dependencies. This should catch issues with updates to packages that already exist on the VMs, such as `wget`.
> [1.7.x] Fix brew when installing existing package

- docs/05_best-practices/08_abi/00_understanding-abi-files.md
- docs/index.md
- examples/kv_map/include/kv_map.hpp
- examples/kv_map/src/kv_map.cpp
- libraries/eosiolib/contracts/eosio/multi_index.hpp
this is the sister PR for https://github.com/EOSIO/eosio.cdt/pull/1023/commits
a few improvements:
- resolves #818, add warning for multi_index::get and multi_index::iterator_to
- correct the link to the built in types
- and improve the kv_map example with a new action that demonstrates input param as user defined type
> [docs] develop branch: add a few improvements for docs

- docs/05_best-practices/08_abi/00_understanding-abi-files.md
- docs/index.md
- examples/kv_map/include/kv_map.hpp
- examples/kv_map/src/kv_map.cpp
- libraries/eosiolib/contracts/eosio/multi_index.hpp
this is a sister PR for https://github.com/EOSIO/eosio.cdt/pull/1028
a few improvements:
- resolves #818, add warning for multi_index::get and multi_index::iterator_to
- correct the link to the built in types 
- and improve the kv_map example with a new action that demonstrates input param as user defined type
> [docs] release/1.8.x add a few improvements for docs

- libraries/eosiolib/contracts/eosio/system.hpp
At present, the documentations for `eosio_exit` accurately describes that the termination is immediate and that destructors etc will not be called however, given that this can lead to very strange error cases it would be better to explicitly mention scenarios where this goes wrong and why.  Ideally, this would be some sort of "big red warning" callout.  
The documentation are updated such that they render an obvious warning about the possible impacts of this intrinsics use describing problems that can occur with write-caches (as we had with the KV singleton), RAII, reference counting etc is attached to this ticket and reviewed for the troubleshooting section
https://blockone.atlassian.net/browse/EPE-382
> Add additional warnings to eosio_exit annotations

- docs.json
- libraries/eosiolib/capi/eosio/db.h
fixes #819
include c api (*.h files) and tell doxygen to ignore the __attribute__ macros
sister PR: https://github.com/EOSIO/eosio.cdt/pull/1036
> [docs] dev - include c api annotations to reference API generation in cdt

- docs.json
- libraries/eosiolib/capi/eosio/db.h
fixes #819
include c api (*.h files) and tell doxygen to ignore the attribute macros
sister PR
https://github.com/EOSIO/eosio.cdt/pull/1035
> [docs] 1.8.x - include c api annotations to reference API generation in cdt 

- .cicd/pipeline.yml
- docs/06_how-to-guides/06_key_value/01_key_value_examples.md
- libraries/eosiolib/contracts/eosio/key_value.hpp
- libraries/eosiolib/contracts/eosio/key_value_singleton.hpp
- tests/unit/test_contracts/kv_bios/kv_bios.cpp
- Match intrinsics of release/2.1.x of EOSIO/eos
- Add `payer` to `kv_set`
- Remove db_name from: `kv_erase, kv_set, kv_get, kv_get_data, kv_it_create`
- The kv_singleton and kv_table interfaces have not changed. `contract_name` is passed for `payer`.
> Add payer to kv_set and remove db_name to match 2.1.x of eosio/eos

- tests/toolchain/abigen-fail/empty_contract.cpp
- tests/toolchain/abigen-fail/empty_contract.json
- tests/toolchain/abigen-fail/empty_contract_with_other_contract.cpp
- tests/toolchain/abigen-fail/empty_contract_with_other_contract.json
- tests/toolchain/abigen-fail/wrong_contract_name.cpp
- tests/toolchain/abigen-fail/wrong_contract_name.json
- tools/cc/eosio-cpp.cpp.in
- tools/include/compiler_options.hpp.in
- tools/include/eosio/gen.hpp
- tools/toolchain-tester/tests.py
- tools/toolchain-tester/testsuite.py
When using `eosio-cpp` to generate WASM and ABI, if the contract is empty, or if the specified contract name doesn't match the real contract name, the ABI will silently not be generated. This fix adds warning output, or throws exception with error messages, for this situation.
Notes: 
- **Only when `--abigen` option is set, the warning or error is output. This is to avoid incompatibility with some previous code (e.g. some contracts in the unit test code have different names for contract and filename). This decision can be further discussed**.
- The `specified` contract name is either explicitly specified by `--contract`, or inferred from output name by `-o`, or the same as the contract filename if neither '--contract' or '-o' is set.
> Add error output when ABI is not generated using "eosio-cpp"

- docs/08_troubleshooting.md
- libraries/eosiolib/core/eosio/name.hpp
- add troubleshooting item for error `system contract must first be initialized`
- fixes #955: the `@cond IMPLEMENTATIONS` was preventing doxygen from parsing the annotation for ""_n opearator
- a few cosmetic changes
sister PR: https://github.com/EOSIO/eosio.cdt/pull/1045
> [docs] develop: add troubleshooting item

- docs/08_troubleshooting.md
- libraries/eosiolib/core/eosio/name.hpp
- add troubleshooting item for error `system contract must first be initialized`
- fixes #955: the `@cond IMPLEMENTATIONS` was preventing doxygen from parsing the annotation for ""_n opearator
- a few cosmetic changes
sister PR: https://github.com/EOSIO/eosio.cdt/pull/1044
> [docs] 1.8.x: add troubleshooting item and fix annotation for ""_n operator

- docs/05_best-practices/09_deferred_transactions.md
fixes #971 [docs] Deferred transaction collisions and NO_DUPLICATE_DEFERRED_ID
sister PR: https://github.com/EOSIO/eosio.cdt/pull/1055
> [docs] 1.8.xdocument deferred transaction collisions

- libraries/eosiolib/capi/eosio/privileged.h
- libraries/eosiolib/contracts/eosio/privileged.hpp
- libraries/native/intrinsics.cpp
- libraries/native/native/eosio/intrinsics_def.hpp
- tests/unit/test_contracts/capi/privileged.c
A new privileged intrinsic with name register_transaction_hook is defined to register a contract callback at the transaction pre-execution phase for all transactions on the chain. 
This will give the system contract the ability to inspect / make modifications to the transaction prior to its execution.  
It is possible that in the future other hook types will be defined.
The interface for the intrinsic is:
`bool register_transaction_hook(transaction_hook hook_type, name callback_contract, name callback_action);`  
where
hook_type, is the type of hook we want to register (currently only one type - preexecution)
callback_contract, is the name of the contract containing the action for the callback
callback_action, is the name of the action inside the contract containing the code for the …
> Add  new intrinsic register_transaction_hook

- libraries/eosiolib/capi/eosio/security_group.h
- libraries/eosiolib/contracts/eosio/security_group.hpp
- libraries/native/intrinsics.cpp
- libraries/native/native/eosio/intrinsics_def.hpp
This PR adds 4 new APIs for security groups.
add_security_group_participants
remove_security_group_participants
in_active_security_group
get_active_security_group
Please refer to the comments of `security_group.hpp` for the detail of the added APIs.
> add security group support

- docs/06_how-to-guides/40_multi-index/how-to-instantiate-a-multi-index-table.md
[docs] 1.8.x  fix typo "privious"->"previous"
fixes #1000
> [docs] 1.8.x fix typo "privious"->"previous"

- docs/05_best-practices/08_abi/01_abi-code-generator-attributes-explained.md
Clean up `[[eosio::action]]` use for structs.
Larry was consulted on this one with DM and he confirmed.
sister PR: https://github.com/EOSIO/eosio.cdt/pull/1077
> [docs] Clean up [[eosio::action]] use for structs

- docs/05_best-practices/08_abi/01_abi-code-generator-attributes-explained.md
Clean up [[eosio::action]] use for structs.
Larry was consulted on this one with DM and he confirmed.
sister PR: https://github.com/EOSIO/eosio.cdt/pull/1076
> [docs] 1.8.x Clean up [[eosio::action]] use for structs

- tools/cc/eosio-cc.cpp.in
- tools/cc/eosio-cpp.cpp.in
Change `clang-7` to `clang-9` that is called by eosio-cpp and eosio-cc for option `-v`.
> Fix the `-v` option of eosio-cpp and eosio-cc to use clang-9

- libraries/eosiolib/tester/crt0.cpp
In WASM files compiled with `-ftester` the `start` function returned void. This made it impossible to access the return value of the `main` function. Now the `start` function passes through the return of `main`.
> Passthrough return of main within start function of tester WASMs.

- docs/03_command-reference/eosio-cpp.md
update eosio-cpp with -no-missing-ricardian-clause
fixes #853
sister PR: https://github.com/EOSIO/eosio.cdt/pull/1118
> [docs] 1.8.x - eosio-cpp add new option

- .cicd/create-docker-from-binary.sh
From [AUTO-1016](https://blockone.atlassian.net/browse/AUTO-1016), we have downstream consumers of our CI systems who may not want to push to DockerHub. This pull request allows these downstream consumers who are running our CI code to push to internal registries exclusively.
> Don't Always Push to DockerHub
