- libraries/eosiolib/multi_index.hpp
> fix for use after free #51

- libraries/eosiolib/time.hpp
> Remove unused declarations.

- libraries/eosiolib/action.h
- libraries/eosiolib/action.hpp
- libraries/eosiolib/db.h
- libraries/eosiolib/multi_index.hpp
- libraries/eosiolib/print.h
- libraries/eosiolib/print.hpp
> Fix issue #211

- libraries/eosiolib/binary_extension.hpp
- libraries/eosiolib/fixed_bytes.hpp
- libraries/eosiolib/fixed_key.hpp
Fixes bugs in `binary_extension`. 
Also fixes small bug in comparison operators of `fixed_bytes` and `fixed_key`.
> binary_extension bug fixes

- libraries/eosiolib/fixed_key.hpp
> fix regression in fixed_key

- libraries/eosiolib/multi_index.hpp
> fix multi_index::begin bug

- libraries/eosiolib/action.h
- libraries/eosiolib/action.hpp
- libraries/eosiolib/chain.h
- libraries/eosiolib/compiler_builtins.h
- libraries/eosiolib/crypto.cpp
- libraries/eosiolib/crypto.h
- libraries/eosiolib/crypto.hpp
- libraries/eosiolib/datastream.hpp
- libraries/eosiolib/db.h
- libraries/eosiolib/eosio.hpp
- libraries/eosiolib/fixed_bytes.hpp
- libraries/eosiolib/fixed_key.hpp
- libraries/eosiolib/memory.h
- libraries/eosiolib/memory.hpp
- libraries/eosiolib/multi_index.hpp
- libraries/eosiolib/name.hpp
- libraries/eosiolib/permission.h
- libraries/eosiolib/permission.hpp
- libraries/eosiolib/print.h
- libraries/eosiolib/print.hpp
- libraries/eosiolib/symbol.hpp
- libraries/eosiolib/system.h
- libraries/eosiolib/transaction.h
- libraries/eosiolib/transaction.hpp
- libraries/eosiolib/types.h
- libraries/eosiolib/varint.hpp
Due to the change of eosio/eos#4969, the path should be updated to renamed license file.
> Update LICENSE path

- libraries/eosiolib/name.hpp
> 4 fix issue #310

- LICENSE
update 2019; 
Format ISO 8869-1;
----------------------------------------------------------------------------------------------------------------------
in Memoriam Guto Schiavon 
R.I.P pioneer and friend. 
#ripGUTO
> Update EOS license year 2019

- libraries/eosiolib/multi_index.hpp
- `uint256_t` -> `checksum256` 
Resolve #332
> Replace references of uint256_t with checksum256

- .buildkite/pipeline.yml
- build.sh
- install.sh
- scripts/eosio_build_amazon.sh
- scripts/eosio_build_centos.sh
- scripts/eosio_build_darwin.sh
- scripts/eosio_build_darwin_deps
- scripts/eosio_build_fedora.sh
- scripts/eosio_build_ubuntu.sh
- uninstall.sh
1. Variables used throughout are now located in build.sh (D.R.Y)
2. CMAKE is now installed into and using ~/lib,bin,etc,data (Eliminates need for root as much as possible)
3. Wrapped apt/yum/brew update with warning
4. Relative build location instead of CMAKE_BINARY_DIR to fix pipeline bug with cp in generate_packages.sh
> V2 build scripts for ci

- scripts/eosiocdt_build.sh
- scripts/eosiocdt_build_amazon.sh
- scripts/eosiocdt_build_centos.sh
- scripts/eosiocdt_build_darwin.sh
- scripts/eosiocdt_build_darwin_deps
- scripts/eosiocdt_build_fedora.sh
- scripts/eosiocdt_build_ubuntu.sh
- scripts/eosiocdt_uninstall.sh
Added sudo back to apt/yum/etc
brew installing cmake
Better logic for seeing existing cmake
Using cd instead of pushd to avoid weird build path in root bug
> Added sudo back + cmake brew + cmake logic change

- docs/guides/generator-attributes.md
> Fix doc typo

- CMakeLists.txt
Changes CMake files to prevent in source builds. Fixes #516
> Prevent in source builds as not to corrupt the directory

- libraries/eosiolib/contracts/eosio/multi_index.hpp
> Fix index_by example

- tools/cc/eosio-cpp.cpp.in
> Fix compilation of contracts without actions

- libraries/eosiolib/multi_index.hpp
Updated details to iterator returns.
Update to multi_index.hpp comments. @brief not found but updated the iterator return types to be more accurate. 
Non
- [x ] Documentation Additions
Auto generation should pick up these changes.
> Update to multi_index comments - updated iterator return types.

- libraries/eosiolib/core/eosio/time.hpp
Adds a missing "check.hpp" include to eosio/time.hpp. Fixes #532
> Add missing "check" include to eosio/time.hpp

- libraries/eosiolib/contracts/eosio/contract.hpp
…lass - showed as dup comment in docs
Update to comment
/**
* %Base class for EOSIO contract.
*
* @ingroup contract
* @details %Base class for EOSIO contract. %A new contract should derive from this class, so it can make use of EOSIO_ABI macro.
*/
becomes 
/**
* %Base class for EOSIO contract.
*
* @ingroup contract
* @details %A new contract should derive from this class, so it can make use of EOSIO_ABI macro.
*/
To stop duplicate wording in docs
> Update to contract.hpp - removing duplicate comment.

- .cicd/pipeline.yml
Removed bash being called before each script.
> Removed explicit calls to bash before scripts.

- .cicd/generate-base-images.sh
- .gitignore
Goal: Remove docker login now that it's in a pre-command hook
https://github.com/EOSIO/auto-gcp-buildfleet/pull/172
https://github.com/EOSIO/auto-gcp-buildfleet/pull/175
https://github.com/EOSIO/eos/pull/7778
https://github.com/EOSIO/eos-vm/pull/78
> [TRAVIS POC] Removed docker login

- scripts/generate_deb.sh
* Lamba handles the addition of the OS on the package name into our artifact storage.
> Removing rename logic.

- tools/external/wabt/src/lexer-source.cc
> Fix compilation issue with GCC-9

- libraries/eosiolib/multi_index.hpp
Fixes #542 - inaccurate documentation
upper_bound revision
> Fix upper_bound documentation 

- libraries/eosiolib/crypto.cpp
Use heap allocation instead of stack allocation when the size of the public key to be recovered using `recover_key` is very large.
Changes build on top of #669.
> Better handling of recover_key for large public keys

- tools/cc/eosio-cpp.cpp.in
- tools/include/compiler_options.hpp.in
> Enforce cxx build when compiling c with eosio-cpp

- tools/include/compiler_options.hpp.in
Fix to default output filename. (when not specified output filename by `-o`)
> Set default output filename

- tools/include/eosio/codegen.hpp
Fix issue with missing dispatcher entries for actions named the same as actions that are available from included contracts.
> Remove filter as the later steps handle this anyway

- tools/include/eosio/codegen.hpp
Fix issue with missing dispatcher entries for actions named the same as actions that are available from included contracts.
> (Release 1.6.x) Remove filter as the later steps handle this anyway 

- .cicd/pipeline.yml
- .cicd/submodule-regression-checker.sh
Fixed two issues with CI:
- Ported changes to submodule regression checks from EOS repository.
- Fix PR builds on Buildkite not working on macOS.
See:
[Build #655](https://buildkite.com/EOSIO/eosio-dot-cdt/builds/655) | This PRs build.
[Build #656](https://buildkite.com/EOSIO/eosio-dot-cdt/builds/656) | A build executed on an open PR that includes these changes applied to develop.
> [1.6.x] Fix broken macOS PR builds on Buildkite

- README.md
Update README.md to use the correct DEB and RPM filenames for wget and installation.  Also, remove delineation between Centos and Fedora packages.  We only now produce one package which is technically for Centos 7.
Also bump version to 1.6.3.
> update README to proper filenames and bump version

- .cicd/helpers/docker-hash.sh
Community members are asking Dev Relations about what eosio/producer is in dockerhub. I'm not sure why we're using it and we need to change it to use the eosio/ci instead.
> [Develop] dockerhub | eosio/producer -> eosio/ci

- .cicd/helpers/docker-hash.sh
Community members are asking Dev Relations about what eosio/producer is in dockerhub. I'm not sure why we're using it and we need to change it to use the eosio/ci instead.
> [1.6.x] dockerhub | eosio/producer -> eosio/ci

- .cicd/helpers/docker-hash.sh
Community members are asking Dev Relations about what eosio/producer is in dockerhub. I'm not sure why we're using it and we need to change it to use the eosio/ci instead.
> [1.7.x] dockerhub | eosio/producer -> eosio/ci

- .cicd/helpers/docker-hash.sh
Community members are asking Dev Relations about what eosio/producer is in dockerhub. I'm not sure why we're using it and we need to change it to use the eosio/ci instead.
> [Master] dockerhub | eosio/producer -> eosio/ci

- .cicd/pipeline.yml
To meet package naming conventions the package should contain el7 instead of centos
> Fix package name

- .cicd/pipeline.yml
10.14.4_6C_14G_40G -> 10.14.6_6C_14G_40G
> [Develop] Upgrade mac anka template to 10.14.6

- .cicd/pipeline.yml
10.14.4_6C_14G_40G -> 10.14.6_6C_14G_40G
> [1.7.x] Upgrade mac anka template to 10.14.6

- .cicd/pipeline.yml
10.14.4_6C_14G_40G -> 10.14.6_6C_14G_40G
> [1.6.x] Upgrade mac anka template to 10.14.6

- .cicd/pipeline.yml
10.14.4_6C_14G_40G -> 10.14.6_6C_14G_40G
> [Master] Upgrade mac anka template to 10.14.6

- tests/toolchain/build-pass/using_std_variant.cpp
- tests/toolchain/build-pass/using_std_variant.json
- tools/include/eosio/abigen.hpp
> Fix "using"  a variant - develop

- tools/include/compiler_options.hpp.in
Expose the option `--only-export` options through ```eosio-cpp``` and ```eosio-ld```.
> expose only-export option through eosio-cpp and eosio-ld

- .cicd/pipeline.yml
- scripts/generate_bottle.sh
Added new Catalina 10.15.0 to the Buildkite CI pipelines.
Added SKIP_MACOS_10_15/14 to match what we use for EOSIO.
> CI/CD support for Catalina

- .cicd/pipeline.yml
- scripts/generate_bottle.sh
> Revert "CI/CD support for Catalina"

- .cicd/docker/amazonlinux-2.dockerfile
- .cicd/docker/centos-7.6.dockerfile
- .cicd/docker/ubuntu-16.04.dockerfile
- .cicd/docker/ubuntu-18.04.dockerfile
- .cicd/pipeline.yml
- .cicd/toolchain-tests.sh
- tests/CMakeLists.txt
- tools/toolchain-tester/main.py
- tools/toolchain-tester/printer.py
- tools/toolchain-tester/toolchain-tester
Adds the Toolchain Tests as a required step in the CI pipeline.
> Toolchain tests CI

- tests/CMakeLists.txt
- tools/toolchain-tester/CMakeLists.txt
- tools/toolchain-tester/toolchain-tester
- tools/toolchain-tester/toolchain-tester.in
> Allow toolchain_tests to work in out-of-tree builds.

- libraries/eosiolib/simple_malloc.cpp
> Realloc should preserve the old memory contents.

- libraries/eosiolib/simple_malloc.cpp
- tests/integration/CMakeLists.txt
- tests/integration/memory_tests.cpp
- tests/unit/test_contracts/malloc_tests.cpp
> Align heap memory to 16 bytes.

- .cicd/pipeline.yml
Updated queues for Buildkite pipeline to match builder and tester fleet used by EOS repository.
See:
https://buildkite.com/EOSIO/eosio-dot-cdt/builds/768 | Build using new fleet.
> [1.7.x] Switch CI fleet.

- .cicd/pipeline.yml
Updated queues for Buildkite pipeline to match builder and tester fleet used by EOS repository.
See:
https://buildkite.com/EOSIO/eosio-dot-cdt/builds/769 | Build using new fleet.
> [1.6.x] Switch CI fleet.

- .cicd/pipeline.yml
Updated queues for Buildkite pipeline to match builder and tester fleet used by EOS repository.
See:
https://buildkite.com/EOSIO/eosio-dot-cdt/builds/770 | Build using new fleet.
> [develop] Switch CI fleet.

- libraries/eosiolib/capi/eosio/action.h
- libraries/eosiolib/capi/eosio/system.h
- libraries/eosiolib/capi/eosio/transaction.h
> Fix capi declarations of functions with no arguments.

- .cicd/pipeline.yml
Updated queues for Buildkite pipeline to match builder and tester fleet used by EOS repository.
See:
https://buildkite.com/EOSIO/eosio-dot-cdt/builds/771 | Build using new fleet.
> [master] Switch CI fleet.

- tools/cc/eosio-cc.cpp.in
- tools/cc/eosio-cpp.cpp.in
- tools/include/compiler_options.hpp.in
- tools/include/eosio/utils.hpp
Subsumes #735 and also fixes -E, -S, -emit-llvm, and -emit-ast.
Fixes #534, #675, #579, and possibly #525
> Handle various command line arguments correctly

- libraries/eosiolib/core/eosio/datastream.hpp
Replace DataStream template parameters with datastream<Stream>, to avoid matching std::basic_ostream.  The linker errors should be fixed by #738.
> Fix for #186

- tests/unit/test_contracts/CMakeLists.txt
- tests/unit/test_contracts/minimal_tests.cpp
- tools/include/eosio/codegen.hpp
> Add attributes for wasm imports in generated code.  Fixes #477.

- libraries/libc++/CMakeLists.txt
> Add missing source, so that unordered_map can link.  Fixes #685.

- tools/include/eosio/utils.hpp
> Detect failure from subprocesses correctly.  Fixes #725.

- libraries/eosiolib/capi/eosio/crypto.h
- libraries/eosiolib/capi/eosio/privileged.h
- libraries/eosiolib/capi/eosio/system.h
- libraries/eosiolib/capi/eosio/transaction.h
- libraries/native/intrinsics.cpp
- tests/integration/capi_tests.cpp
- tests/integration/contracts.hpp.in
- tests/unit/test_contracts/CMakeLists.txt
- tests/unit/test_contracts/capi/action.c
- tests/unit/test_contracts/capi/capi.c
- tests/unit/test_contracts/capi/capi_tests.abi
- tests/unit/test_contracts/capi/chain.c
- tests/unit/test_contracts/capi/crypto.c
- tests/unit/test_contracts/capi/db.c
- tests/unit/test_contracts/capi/permission.c
- tests/unit/test_contracts/capi/print.c
- tests/unit/test_contracts/capi/privileged.c
- tests/unit/test_contracts/capi/system.c
- tests/unit/test_contracts/capi/transaction.c
> Fix C++isms in the C api.

- docs/index.md
- braking -> breaking 
- Fixed a broken sentence.
> Fix typo and grammar in 1.7 release docs 

- libraries/eosiolib/core/eosio/symbol.hpp
- libraries/eosiolib/symbol.hpp
The current definition will produce an ABI for extended_symbol that will fail in abi_serializer.
> fix for extended symbol 1.6.x

- tests/integration/CMakeLists.txt
- tests/integration/capi_tests.cpp
- tests/integration/codegen_tests.cpp
- tests/integration/memory_tests.cpp
Add missing `BOOST_AUTO_TEST_SUITE_END()` and change CMake so that the tests are in the correct hierarchy and have the correct labels for ctest.
> Fix integration test hierarchy.

- libraries/eosiolib/core/eosio/symbol.hpp
The current definition will produce an ABI for extended_symbol that will fail in abi_serializer.
> fix for extended_symbol

- tools/include/compiler_options.hpp.in
> Fix extra spaces in options for wasm-ql

- docs.json
> Missing docs.json config

- libraries/eosiolib/core/eosio/binary_extension.hpp
- tests/unit/binary_extension_tests.cpp
Fixes issues with copy assignment and move assignment.
> binary_extension fixes (develop)

- libraries/eosiolib/core/eosio/binary_extension.hpp
Patch `constexpr binary_extension& operator = (binary_extension&& other)` to `return *this`.
> [develop] Patch `binary_extension` assignment operator

- libraries/eosiolib/core/eosio/binary_extension.hpp
- tests/unit/binary_extension_tests.cpp
Fixes issues with copy assignment and move assignment.
> [release/1.6.x] `binary_extension` fixes

- libraries/eosiolib/core/eosio/binary_extension.hpp
- tests/unit/binary_extension_tests.cpp
Fixes issues with copy assignment and move assignment.
> [release/1.7.x] `binary_extension` fixes

- libraries/eosiolib/core/eosio/name.hpp
- tests/unit/name_tests.cpp
Implementation of add .prefix() expression to {name}  #648
> Add prefix expression to name

- libraries/eosiolib/core/eosio/time.hpp
- libraries/libc++/CMakeLists.txt
- tests/unit/time_tests.cpp
Add support for creation of a time_point_sec from an iso string #747
> Add support for creation of a time_point_sec from an iso string

- libraries/eosiolib/contracts/eosio/key_value.hpp
- tests/integration/kv_tests.cpp
- tests/unit/test_contracts/kv_single_index_tests.cpp
> Serialize non-variants as 0 index variant for upgrade compatibility

- docs/05_best-practices/08_abi/00_understanding-abi-files.md
Fixes #787 
Migrate ABI guide to eosio.cdt documentation
> [docs] migrate ABI guide to eosio.cdt documentation

- tools/include/eosio/codegen.hpp
…to worry about fully qualified names
> fix action_results

- tests/toolchain/abigen-pass/action_results_test.abi
- tests/toolchain/abigen-pass/action_results_test.cpp
- tools/include/eosio/abigen.hpp
Forgot to add the struct of return type to ABI, if needed.
> forgot to add the struct of the return type as possible struct type

- libraries/eosiolib/contracts/eosio/key_value.hpp
- tests/integration/kv_tests.cpp
- tests/integration/main.cpp
- tests/unit/test_contracts/kv_make_key_tests.cpp
- tests/unit/test_contracts/kv_multiple_indices_tests.cpp
- tests/unit/test_contracts/kv_single_index_tests.cpp
Add support for unique and non-unique indexes.
> Add support for unique and non-unique indexes.

- scripts/eosiocdt_build_darwin.sh
Cherry picked fix from `develop`.  See #856
> Building on macOS with no dependencies installed did not work.

- .cicd/pipeline.yml
- Updated Catalina Mac builds to 10.15.4.
- Updated Anka plugins to latest version.
- Made skip Mac flags consistent.
> [develop] Bump Catalina version.

- docs/06_how-to-guides/06_key_value/01_key_value_examples.md
Update kv_table Example including:
* Use up-to-date header
* Fix minor C++ syntax
* Update the member variable reference used for index
> Update kv_table example

- tools/include/compiler_options.hpp.in
Add a flag to allow the generation of a wasm with function and elem names.
> Add allow names flag

- tools/include/eosio/codegen.hpp
> Don't rewrite #includes that are already absolute paths.

- libraries/eosiolib/contracts/eosio/multi_index.hpp
Fix use-after-free in multi_index
> Fix use-after-free

- docs/03_command-reference/eosio-init.md
Resolves #883, correction for eosio-init example.
> [docs] correction for eosio-init example in release-1.7.x

- libraries/eosiolib/contracts/eosio/key_value.hpp
Fix memory bug in key_value.hpp
> Fix memory bug in key_value.hpp

- libraries/eosiolib/contracts/eosio/key_value.hpp
> Fix memory bug (another spot) in key_value.hpp

- libraries/eosiolib/tester/eosio/tester.hpp
- libraries/eosiolib/tester/tester.cpp
- tests/tester/tester.cpp
- tests/unit/test_contracts/tester_tests.cpp
- tests/unit/test_contracts/tester_tests.hpp
- tools/include/eosio/gen.hpp
> Add CDT support for the tester's sign intrinsic.

- docs/06_how-to-guides/02_multi-index/how-to-define-a-singleton.md
- examples/singleton_example/include/singleton_example.hpp
- examples/singleton_example/src/singleton_example.cpp
the changes simplify the singleton example and they also update the related docs to reflect the changes in the code example.
fixes #888 [docs] Suggestion / Change Request for singleton example and docs
> [docs] Suggestion / Change Request for singleton example and docs

- libraries/boost/include/boost/hana/functional/curry.hpp
> Fix duplicate symbol error with hana

- docs/06_how-to-guides/02_multi-index/how-to-define-a-singleton.md
- examples/singleton_example/include/singleton_example.hpp
- examples/singleton_example/src/singleton_example.cpp
the changes simplify the singleton example and they also update the related docs to reflect the changes in the code example.
fixes #888 [docs] Suggestion / Change Request for singleton example and docs
sibling PR: https://github.com/EOSIO/eosio.cdt/pull/908
> [docs] release/1.7.x Suggestion / Change Request for singleton example and docs

- libraries/eosiolib/contracts/eosio/multi_index.hpp
fixes #904 (upper and lower bound need some lovin')
> docs - 1.7.x repo - update the upper_bound and lower_bound annotation

- docs/guides/basic-usage.md
> [docs] Fix broken links in basic usage section - 1.5

- examples/hello/include/hello.hpp
- examples/hello/src/hello.cpp
update hello example contract to demonstrate return values form action
> [docs] update hello example contract to demonstrate return values form action

- docs/index.md
> [docs] Fix broken links in main index section - 1.7

- docs/index.md
Up-port of PR #937 to develop
Resolves #936
> [docs] Fix broken links in main index section

- docs/05_best-practices/08_abi/01_abi-code-generator-attributes-explained.md
- docs/05_best-practices/08_abi/02_manually_write_an_ABI_file_explained.md
Up-port of PR #945 to develop
Resolves #939
> [docs] Fix Broken links in best practices section

- .cicd/pipeline.yml
> Bump pipeline timeout

- tests/toolchain/build-pass/bool_template.cpp
- tests/toolchain/build-pass/bool_template.json
- tools/include/eosio/codegen.hpp
> Better fix for booleans as template arguments

- tests/unit/test_contracts/kv_multiple_indices_tests.cpp
Somehow CI didn't catch this, or a merge wasn't correctly blocked on failing tests.
> Fix missing put in kv tests

- tests/integration/action_results_test.cpp
- tests/integration/capi_tests.cpp
- tests/integration/codegen_tests.cpp
- tests/integration/kv_tests.cpp
- tests/integration/memory_tests.cpp
> Fix integration test issue with N() macro

- .cicd/docker/ubuntu-20.04.dockerfile
- .cicd/pipeline.yml
> Add support for Ubuntu 20.04 in the CI pipeline

- tests/toolchain/abigen-pass/key_value.abi
- tools/include/eosio/abigen.hpp
> Fix abi names in KV

- docs.json
- docs/06_how-to-guides/05_how-to-write-an-abi-file.md
- examples/kv_addr_book/include/kv_addr_book.hpp
update for the following:
* the kv_addr_book example smart contract 
* and the kv ABI
> [docs] update the kv_addr_book example smart contract and the kv  ABI

- .cicd/docker/amazonlinux-2.dockerfile
- .cicd/docker/centos-7.7.dockerfile
- .cicd/docker/ubuntu-16.04.dockerfile
- .cicd/docker/ubuntu-18.04.dockerfile
- .cicd/toolchain-tests.sh
- libraries/eosiolib/contracts/eosio/key_value.hpp
- tools/toolchain-tester/toolchain-tester.in
`partial_key`/`full_key` didn't make it into develop, so this is only needed in `staging-c`
> key() should return a full_key, not a partial_key.

- examples/kv_addr_book/include/kv_addr_book.hpp
- examples/kv_addr_book/src/kv_addr_book.cpp
going full swing into the "explicit code" direction, make use everywhere of `std::` and `eosio::`
> [docs] updates on the example kv smart contract

- examples/kv_addr_book/include/kv_addr_book.hpp
- examples/kv_addr_book/src/kv_addr_book.cpp
re-working the kv examples to conform with the latest version of kv api
> [docs] re-working the kv examples to conform with the latest version of kv api

- examples/multi_index_large/CMakeLists.txt
- examples/multi_index_large/README.txt
- examples/multi_index_large/include/multi_index_large.hpp
- examples/multi_index_large/ricardian/multi_index_large.contracts.md
- examples/multi_index_large/src/CMakeLists.txt
- examples/multi_index_large/src/multi_index_large.cpp
multi index smart contract for dogfooding test
> Multi index large

- examples/kv_todo/CMakeLists.txt
- examples/kv_todo/README.txt
- examples/kv_todo/include/kv_todo.hpp
- examples/kv_todo/ricardian/kv_todo.contracts.md
- examples/kv_todo/src/CMakeLists.txt
- examples/kv_todo/src/kv_todo.cpp
Fixed and added kv_todo smart contract.
-fixed init call
-fixed non-unique field order
> fix kv_todo

- examples/kv_addr_book/include/kv_addr_book.hpp
- examples/kv_table_tests/src/kvtest.cpp
- examples/kv_todo/include/kv_todo.hpp
updated kv tables  examples codes with new map api
#include <eosio/table.hpp>
replaced eosio::non_unique with std::tuple
> updted kv examples

- libraries/eosiolib/contracts/eosio/key_value.hpp
The `index` member was left uninitialized.
> Fix KV iterator move

- libraries/eosiolib/contracts/eosio/eosio.hpp
- libraries/eosiolib/contracts/eosio/map.hpp
- libraries/eosiolib/contracts/eosio/producer_schedule.hpp
- libraries/eosiolib/core/eosio/check.hpp
- libraries/eosiolib/core/eosio/key_utils.hpp
- libraries/eosiolib/core/eosio/name.hpp
- libraries/eosiolib/core/eosio/reflect.hpp
- libraries/eosiolib/eosiolib.cpp
- tests/integration/kv_tests.cpp
- tests/unit/test_contracts/kv_map_tests.cpp
During some dogfooding by b1bart.  We uncovered a few simple bugs.  These are the quick fixes and associated tests that should've been there to begin with and some to ensure we don't regress.
> KV map fixes

- docs/06_how-to-guides/30_key-value-api/kv_map/10_how-to-use-kv-map.md
- docs/06_how-to-guides/30_key-value-api/kv_map/30_how-to-upsert-into-kv-map.md
- docs/06_how-to-guides/30_key-value-api/kv_map/70_how-to-find-in-kv-map.md
- docs/06_how-to-guides/30_key-value-api/kv_map/90_how-to-allow-users-to-pay-kv-map.md
- docs/06_how-to-guides/30_key-value-api/kv_table/10_how-to-use-kv-table.md
- docs/06_how-to-guides/30_key-value-api/kv_table/20_how-to-create-indexes-kv-table.md
- docs/06_how-to-guides/30_key-value-api/kv_table/30_how-to-upsert-into-kv-table.md
- docs/06_how-to-guides/30_key-value-api/kv_table/40_how-to-delete-from-kv-table.md
- docs/06_how-to-guides/30_key-value-api/kv_table/70_how-to-find-in-kv-table.md
- docs/06_how-to-guides/30_key-value-api/kv_table/90_how-to-allow-users-to-pay-kv-table.md
add more links between kv api documents
the corresponding PR which merges to develop branch:
https://github.com/EOSIO/eosio.cdt/pull/1015
> [docs] v1.8.x add more links between kv api documents

- docs/06_how-to-guides/30_key-value-api/kv_map/10_how-to-use-kv-map.md
- docs/06_how-to-guides/30_key-value-api/kv_map/30_how-to-upsert-into-kv-map.md
- docs/06_how-to-guides/30_key-value-api/kv_map/70_how-to-find-in-kv-map.md
- docs/06_how-to-guides/30_key-value-api/kv_map/90_how-to-allow-users-to-pay-kv-map.md
- docs/06_how-to-guides/30_key-value-api/kv_table/10_how-to-use-kv-table.md
- docs/06_how-to-guides/30_key-value-api/kv_table/20_how-to-create-indexes-kv-table.md
- docs/06_how-to-guides/30_key-value-api/kv_table/30_how-to-upsert-into-kv-table.md
- docs/06_how-to-guides/30_key-value-api/kv_table/40_how-to-delete-from-kv-table.md
- docs/06_how-to-guides/30_key-value-api/kv_table/70_how-to-find-in-kv-table.md
- docs/06_how-to-guides/30_key-value-api/kv_table/90_how-to-allow-users-to-pay-kv-table.md
add more links between kv api documents
> [docs] dev: add more links between kv api documents

- docs/06_how-to-guides/30_key-value-api/kv_map/10_how-to-use-kv-map.md
- docs/06_how-to-guides/30_key-value-api/kv_map/30_how-to-upsert-into-kv-map.md
- docs/06_how-to-guides/30_key-value-api/kv_map/70_how-to-find-in-kv-map.md
- docs/06_how-to-guides/30_key-value-api/kv_map/90_how-to-allow-users-to-pay-kv-map.md
- docs/06_how-to-guides/30_key-value-api/kv_table/10_how-to-use-kv-table.md
- docs/06_how-to-guides/30_key-value-api/kv_table/20_how-to-create-indexes-kv-table.md
- docs/06_how-to-guides/30_key-value-api/kv_table/30_how-to-upsert-into-kv-table.md
- docs/06_how-to-guides/30_key-value-api/kv_table/40_how-to-delete-from-kv-table.md
- docs/06_how-to-guides/30_key-value-api/kv_table/70_how-to-find-in-kv-table.md
- docs/06_how-to-guides/30_key-value-api/kv_table/90_how-to-allow-users-to-pay-kv-table.md
add more links between kv api documents
sister PR: https://github.com/EOSIO/eosio.cdt/pull/1015
> [docs] add more links between kv api documents

- .cicd/pipeline.yml
Add the Ubuntu 20.04 binary package for EOSIO.CDT v1.8.x
After test the deb package works on a clean 20.04 cloud instance .
> Add the Ubuntu 20.04 binary package for EOSIO.CDT v1.8.x

- .cicd/pipeline.yml
We've had reports of Mac build failures in overnight builds. This appears to be caused by Homebrew reporting an error when attempting to install a package that already exists, but is an older version. This change fixes this by executing `brew upgrade` before installing our dependencies. This should catch issues with updates to packages that already exist on the VMs, such as `wget`.
> [develop] Fix brew when installing existing package

- docs/02_installation.md
- docs/06_how-to-guides/40_multi-index/how-to-modify-data-in-a-multi-index-table.md
update links and list of tools as a bullet list
resolves #861
sister PR #1031
sister PR #1032
> [docs] develop branch - update links and list of tools as a bullet list 

- docs/02_installation.md
- docs/06_how-to-guides/02_multi-index/how-to-modify-data-in-a-multi-index-table.md
update links and list of tools as a bullet list
resolves #861
sister PR https://github.com/EOSIO/eosio.cdt/pull/1031
> [docs] 1.7.x update links and list of tools as a bullet list

- .cicd/docker/centos-8.dockerfile
- .cicd/docker/ubuntu-20.04.dockerfile
- .cicd/package.sh
- .cicd/pipeline.yml
- scripts/eosiocdt_build_centos.sh
- scripts/eosiocdt_build_ubuntu.sh
Adding targets ubuntu 16.04, ubuntu 20.04, centos 8, and amazon_linux 2 for eosio.cdt 1.6.x.
> Adding more OS support to eosio.cdt 1.7.x

- libraries/eosiolib/capi/eosio/privileged.h
- libraries/eosiolib/contracts/eosio/privileged.hpp
- libraries/native/intrinsics.cpp
- libraries/native/native/eosio/intrinsics_def.hpp
- tests/unit/test_contracts/capi/privileged.c
Set transaction payer intrinsic implementation for the Transaction Sponsorship feature.
set_transaction_resource_payer intrinsic is added.
Please add the new intrinsic to CDT documentation, for contract developers use.
> Set transaction payer intrinsic implementation

- .cicd/pipeline.yml
Changes to Homebrew's package management have broken Mac builds where we have Homebrew pre-installed. We'll need to run `brew update`, then `brew upgrade` to update Homebrew properly before trying to install or update any packages in the build process.
> [develop] Update brew steps

- .cicd/pipeline.yml
Changes to Homebrew's package management have broken Mac builds where we have Homebrew pre-installed. We'll need to run `brew update`, then `brew upgrade` to update Homebrew properly before trying to install or update any packages in the build process.
> [r1.8] Update brew steps 

- .cicd/pipeline.yml
Changes to Homebrew's package management have broken Mac builds where we have Homebrew pre-installed. We'll need to run `brew update`, then `brew upgrade` to update Homebrew properly before trying to install or update any packages in the build process.
> [r1.7] Update brew steps 

- .cicd/pipeline.yml
Changes to Homebrew's package management have broken Mac builds where we have Homebrew pre-installed. We'll need to run `brew update`, then `brew upgrade` to update Homebrew properly before trying to install or update any packages in the build process.
> Update brew steps 

- docs/06_how-to-guides/10_compile/01_compile-a-contract-via-cli.md
- docs/06_how-to-guides/10_compile/02_how-to-configure-cmake.md
- docs/06_how-to-guides/10_compile/03_compiling-contracts-with-cmake.md
- docs/06_how-to-guides/20_authorization/how_to_restrict_access_to_an_action_by_user.md
- docs/06_how-to-guides/30_key-value-api/kv_map/10_how-to-use-kv-map.md
- docs/06_how-to-guides/30_key-value-api/kv_map/30_how-to-upsert-into-kv-map.md
- docs/06_how-to-guides/30_key-value-api/kv_map/40_how-to-delete-from-kv-map.md
- docs/06_how-to-guides/30_key-value-api/kv_map/50_how-to-iterate-kv-map.md
- docs/06_how-to-guides/30_key-value-api/kv_map/70_how-to-find-in-kv-map.md
- docs/06_how-to-guides/30_key-value-api/kv_map/90_how-to-allow-users-to-pay-kv-map.md
- docs/06_how-to-guides/30_key-value-api/kv_table/10_how-to-use-kv-table.md
- docs/06_how-to-guides/30_key-value-api/kv_table/20_how-to-create-indexes-kv-table.md
- docs/06_how-to-guides/30_key-value-api/kv_table/30_how-to-upsert-into-kv-table.md
- docs/06_how-to-guides/30_key-value-api/kv_table/40_how-to-delete-from-kv-table.md
- docs/06_how-to-guides/30_key-value-api/kv_table/50_how-to-iterate-kv-table.md
- docs/06_how-to-guides/30_key-value-api/kv_table/60_how-to-check-a-record-kv-table.md
- docs/06_how-to-guides/30_key-value-api/kv_table/70_how-to-find-in-kv-table.md
- docs/06_how-to-guides/30_key-value-api/kv_table/80_how-to-query-range-in-kv-table.md
- docs/06_how-to-guides/30_key-value-api/kv_table/90_how-to-allow-users-to-pay-kv-table.md
- docs/06_how-to-guides/50_how-to-create-and-use-action-wrappers.md
- docs/06_how-to-guides/60_how-to-return-values-from-actions.md
- docs/09_tutorials/03_create-an-abi-file.md
- docs/09_tutorials/index.md
dev branch - updates to match newest how to template
> [docs] dev branch - updates to match newest how to template

- docs/06_how-to-guides/40_multi-index/how-to-instantiate-a-multi-index-table.md
[docs] fix typo "privious"->"previous"
fixes #1000
> [docs] fix typo "privious"->"previous"

- tests/unit/name_tests.cpp
- tests/unit/string_tests1.cpp
- tests/unit/string_tests2.cpp
break up name_tests into smaller tests, rename string_tests, remove static keyword from variables
None
> Refactor unit tests

- docs/06_how-to-guides/10_compile/01_compile-a-contract-via-cli.md
- docs/06_how-to-guides/10_compile/02_how-to-configure-cmake.md
- docs/06_how-to-guides/10_compile/03_compiling-contracts-with-cmake.md
- docs/06_how-to-guides/20_authorization/how_to_restrict_access_to_an_action_by_user.md
- docs/06_how-to-guides/30_key-value-api/kv_map/10_how-to-use-kv-map.md
- docs/06_how-to-guides/30_key-value-api/kv_map/30_how-to-upsert-into-kv-map.md
- docs/06_how-to-guides/30_key-value-api/kv_map/40_how-to-delete-from-kv-map.md
- docs/06_how-to-guides/30_key-value-api/kv_map/50_how-to-iterate-kv-map.md
- docs/06_how-to-guides/30_key-value-api/kv_map/70_how-to-find-in-kv-map.md
- docs/06_how-to-guides/30_key-value-api/kv_map/90_how-to-allow-users-to-pay-kv-map.md
- docs/06_how-to-guides/30_key-value-api/kv_table/10_how-to-use-kv-table.md
- docs/06_how-to-guides/30_key-value-api/kv_table/20_how-to-create-indexes-kv-table.md
- docs/06_how-to-guides/30_key-value-api/kv_table/30_how-to-upsert-into-kv-table.md
- docs/06_how-to-guides/30_key-value-api/kv_table/40_how-to-delete-from-kv-table.md
- docs/06_how-to-guides/30_key-value-api/kv_table/50_how-to-iterate-kv-table.md
- docs/06_how-to-guides/30_key-value-api/kv_table/60_how-to-check-a-record-kv-table.md
- docs/06_how-to-guides/30_key-value-api/kv_table/70_how-to-find-in-kv-table.md
- docs/06_how-to-guides/30_key-value-api/kv_table/80_how-to-query-range-in-kv-table.md
- docs/06_how-to-guides/30_key-value-api/kv_table/90_how-to-allow-users-to-pay-kv-table.md
- docs/06_how-to-guides/50_how-to-create-and-use-action-wrappers.md
- docs/06_how-to-guides/60_how-to-return-values-from-actions.md
- docs/09_tutorials/03_create-an-abi-file.md
- docs/09_tutorials/index.md
release 1.8.x - updates to match newest how to template
this PR has all changes from sister PR
and updated the cdt/latest path to cdt/v1.8 paths
sister PR: https://github.com/EOSIO/eosio.cdt/pull/1083
> [docs] 1.8.x - updates to match newest how to template

- docs/06_how-to-guides/40_multi-index/how-to-instantiate-a-multi-index-table.md
> [docs] update Info->info

- docs/06_how-to-guides/40_multi-index/how-to-instantiate-a-multi-index-table.md
> [docs] Info -> info

- docs/06_how-to-guides/40_multi-index/how-to-define-a-primary-index.md
- docs/06_how-to-guides/40_multi-index/how-to-define-a-secondary-index.md
- docs/06_how-to-guides/40_multi-index/how-to-define-a-singleton.md
- docs/06_how-to-guides/40_multi-index/how-to-delete-data-from-a-multi-index-table.md
- docs/06_how-to-guides/40_multi-index/how-to-insert-data-into-a-multi-index-table.md
- docs/06_how-to-guides/40_multi-index/how-to-instantiate-a-multi-index-table.md
- docs/06_how-to-guides/40_multi-index/how-to-iterate-and-retrieve-a-multi_index-table-based-on-secondary-index.md
- docs/06_how-to-guides/40_multi-index/how-to-iterate-and-retrieve-a-multi_index-table.md
- docs/06_how-to-guides/40_multi-index/how-to-modify-data-in-a-multi-index-table.md
- docs/09_tutorials/02_abi-variants.md
informational callouts fixed for multi index how to pages
sister PR: https://github.com/EOSIO/eosio.cdt/pull/1094
> [docs] dev - fix informational callouts

- docs/03_command-reference/eosio-cpp.md
update eosio-cpp with -no-missing-ricardian-clause
fixes #853 
sister PR: https://github.com/EOSIO/eosio.cdt/pull/1119
> [docs] dev: update eosio-cpp with -no-missing-ricardian-clause

- .cicd/pipeline.yml
Add release 1.7.x brew updater step in CICD pipeline.
> Release 1.7.x brew updater

- .cicd/pipeline.yml
Add release 1.8.x brew updater step in CICD pipeline.
> Release 1.8.x brew updater

- .cicd/pipeline.yml
Add develop brew updater step in CICD pipeline.
> Develop brew updater

- .cicd/pipeline.yml
Tests can run on lighter node pool which has more availability.
> Release 1.8.x nodes

- .cicd/pipeline.yml
Unit tests can run on lighter node pool which has more availability.
> Unit tests can run on lighter node pool.

- .cicd/pipeline.yml
Allow timeout override for Mojave package builder step.
> Allow timeout override for Mojave package builder step.

- .cicd/pipeline.yml
Tests can run on lighter node pool which has more availability.
> Tests can run on lighter node pool which has more availability.

- .cicd/pipeline.yml
Ensure timeout can be overridden for macos package building.
> Ensure timeout can be overridden for macos package building.

- .cicd/pipeline.yml
Ensure timeout can be overridden for macos package building.
> Ensure timeout can be overridden for macos package builder.

- docs/06_how-to-guides/02_multi-index/how-to-instantiate-a-multi-index-table.md
correct code vs scope in multi-index how to
sister PR: https://github.com/EOSIO/eosio.cdt/pull/1135
> [docs] 1.7.x correct code vs scope in multi-index how to

- docs/06_how-to-guides/40_multi-index/how-to-instantiate-a-multi-index-table.md
correct code vs scope in multi-index how to
sister PR: https://github.com/EOSIO/eosio.cdt/pull/1136
> [docs] 1.8.x correct code vs scope in multi-index how to

- docs/06_how-to-guides/40_multi-index/how-to-instantiate-a-multi-index-table.md
small correction based on peer review - Bob
> small correction based on peer review

- .cicd/pipeline.yml
- .cicd/test-package.run.sh
- .cicd/test-package.sh
Add test steps for package artifacts.
> Add test steps for package artifacts.

- .cicd/pipeline.yml
- .cicd/test-package.run.sh
- .cicd/test-package.sh
Add test steps for staging-c package artifacts.
> Add test steps for staging-c package artifacts.

- .cicd/pipeline.yml
- .cicd/test-package.run.sh
- .cicd/test-package.sh
Add test steps for 1.8.x package artifacts.
> Add test steps for 1.8.x package artifacts.

- .cicd/pipeline.yml
- .cicd/test-package.run.sh
- .cicd/test-package.sh
Add test steps for 1.7.x package artifacts.
> Add test steps for 1.7.x package artifacts.

- tests/CMakeLists.txt
- tests/unit/version_tests.sh
Update binary version test to take raw version tag version for easier cicd-isms.
> Update binary version test to take raw version tag version for easier cicd-isms.

- scripts/generate_bottle.sh
> fix homebrew warnings

- scripts/generate_bottle.sh
Homebrew 2.6 removed support for High Sierra so Mojave needs to be depedency
> fix homebrew again - remove High Sierra support 

- docs/05_features/10_resource_payer.md
add correct link to the eosjs documentation page
> [docs] add correct link to the eosjs documentation page
